[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
mysql = "26.0"
sha3 = "0.10.8"
rand = "0.9.1"
base64 = "0.22.1"