[package]
name = "email_encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = "0.11"
url = "2"
openssl = "0.10.71"
base64 = "0.22.1"
mail-parser = "0.10.2"
dotenvy = "0.15.7"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
rand = "0.9.1"